services/dashboard/src/__init__.py
from flask import Flask
from src.config import Config
from flask_pymongo import PyMongo

mongo = PyMongo()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    app.config["MONGO_URI"] = "mongodb://dev:dev@localhost:27017/dev?authSource=admin"

    mongo.init_app(app)

    from .main.routes import main
    from .errors.handlers import errors

    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

services/dashboard/src/main/routes.py
import random

from datetime import datetime
from datetime import timedelta, timezone
from flask import render_template, jsonify, Blueprint
from src import mongo

main = Blueprint("main", __name__)


@main.route("/")
def home():
    return render_template("home.html")


@main.route("/about/")
def about():
    return render_template("about.html")


@main.route("/contact/")
def contact():
    return render_template("contact.html")


@main.route("/api/data")
def get_data():

    data = mongo.db.telemetry.find(
        {"timestamp": {"$gt": datetime.utcnow() - timedelta(seconds=2)}}
    )

    raw_data = list(data)

    data = {
        "x": str(raw_data[0]["timestamp"].replace(tzinfo=timezone.utc).isoformat()),
        "y": [raw_data[0]["value"]],
    }

    return jsonify(data)

services/dashboard/src/templates/about.html
{% extends "layout.html" %}
{% block title %}
About us
{% endblock %}
{% block content %}
<h1 class="mt-5">A Title</h1>
<p class="lead">About page for the Visual Studio Code Flask tutorial.</p>
{% endblock %}

services/dashboard/src/templates/contact.html
{% extends "layout.html" %}
{% block title %}
Contact us
{% endblock %}
{% block content %}
<h1 class="mt-5">A Title</h1>
<p class="lead">Contact page for the Visual Studio Code Flask tutorial.</p>
{% endblock %}

services/dashboard/src/templates/home.html
{% extends "layout.html" %}
{% block title %}
Home
{% endblock %}
{% block content %}

<h1 class="mt-5">Dashboard</h1>

<p class="lead">Below is some data.</p>

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <canvas id="myChart"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups"
                style="justify-content: center; display: flex;">
                <div class="btn-group me-2" role="group" aria-label="First group">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            set duration
                        </button>
                        <ul id="duration-options" class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" href="#">15 minutes</a></li>
                            <li><a class="dropdown-item" href="#">10 minutes</a></li>
                            <li><a class="dropdown-item" href="#">5 minutes</a></li>
                            <li><a class="dropdown-item" href="#">2 minutes</a></li>
                            <li><a class="dropdown-item" href="#">1 minute</a></li>
                        </ul>
                    </div>
                </div>
                <div class="btn-group me-2" role="group" aria-label="Second group">
                    <button type="button" class="btn btn-secondary" onclick="handlePauseOnOff()">pause on/off</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    var chartColors = {
        red: 'rgb(255, 99, 132)',
        orange: 'rgb(255, 159, 64)',
        yellow: 'rgb(255, 205, 86)',
        green: 'rgb(75, 192, 192)',
        blue: 'rgb(54, 162, 235)',
        purple: 'rgb(153, 102, 255)',
        grey: 'rgb(201, 203, 207)'
    };

    function onRefresh(chart) {
        const dataAPI = `${window.origin}/api/data`;
        $.getJSON(dataAPI, function (result) {
            chart.data.datasets.forEach(function (dataset, i) {
                var dt = Date.parse(result.x);
                dataset.data.push({
                    x: dt,
                    y: result.y[i]
                });
            });
        });
    }

    var color = Chart.helpers.color;

    const data = {
        datasets: [{
            label: 'Dataset 1 (linear interpolation)',
            backgroundColor: color(chartColors.red).alpha(0.5).rgbString(),
            borderColor: chartColors.red,
            fill: false,
            lineTension: 0,
            borderDash: [8, 4],
            data: []
        }, {
            label: 'Dataset 2 (cubic interpolation)',
            backgroundColor: color(chartColors.blue).alpha(0.5).rgbString(),
            borderColor: chartColors.blue,
            fill: false,
            cubicInterpolationMode: 'monotone',
            data: []
        }]
    };

    const config = {
        type: 'line',
        data: data,
        options: {
            scales: {
                x: {
                    type: 'realtime',
                    realtime: {
                        duration: 60000 * 15,  // 15 mins
                        ttl: 60000 * 15,
                        refresh: 1000,
                        delay: 4000,
                        onRefresh: onRefresh
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Value'
                    }
                }
            },
            interaction: {
                intersect: false
            },
            plugins: {
                zoom: {
                    pan: {
                        enabled: true,
                        mode: 'x'
                    },
                    zoom: {
                        pinch: {
                            enabled: true
                        },
                        wheel: {
                            enabled: true
                        },
                        mode: 'x'
                    },
                    limits: {
                        x: {
                            minDelay: 4000,
                            minDuration: 60000,
                            maxDuration: 60000 * 15  // 15 mins
                        }
                    }
                }
            }
        }
    };

    window.onload = function () {
        var ctx = document.getElementById('myChart').getContext('2d');
        window.myChart = new Chart(ctx, config);
    };

    // pauses/unpauses the chart
    const handlePauseOnOff = function () {
        myChart.options.scales.x.realtime.pause = !myChart.options.scales.x.realtime.pause;
        myChart.update('none');
    };

    // Sets the duration for the chart using options from the dropdown menu
    $('#duration-options li').on('click', function (e) {
        e.preventDefault();
        var text = $(this).text();
        var duraction = parseInt(text.split(' ')[0]);
        myChart.options.scales.x.realtime.duration = 60000 * duraction;
        myChart.update('none');
    });

</script>

{% endblock %}

services/dashboard/src/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="#">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='site.css') }}" />
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/luxon@2.3.0/build/global/luxon.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@1.1.0/dist/chartjs-adapter-luxon.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.7"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-zoom@1.2.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-streaming@2.0.0"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000;">
            <div class="container-fluid">
                <a href="{{ url_for('main.home') }}" class="navbar-brand">Data Displayer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item active">
                            <a href="{{ url_for('main.home') }}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a href="{{ url_for('main.about') }}" class="nav-link">About</a>
                        </li>
                        <li class="nav-item active">
                            <a href="{{ url_for('main.contact') }}" class="nav-link">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        {% block content %}
        {% endblock %}
        <hr />
    </main>

    <footer class="footer">
        <div class="container">
            <p><a href="https://www.colorado.edu/"><img src="../static/cu_boulder_logo.svg" alt="Bootstrap" width="32"
                        height="32"></a> &copy; University of Colorado Boulder</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>

</html>